name: safestep
description: "A new Flutter project for personal safety."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.8
  geolocator: ^14.0.2
  flutter_map: ^8.0.0
  latlong2: ^0.9.1
  geocoding: ^3.0.0
  # The Core must be 4.3.0 for the new Firestore to work
  firebase_core: ^4.3.0
  
  # This version is compatible with Core 4.3.0
  firebase_auth: ^6.1.3
  
  # Kept exactly as requested
  google_sign_in: ^7.2.0
  
  # Now this will resolve correctly
  cloud_firestore: ^6.1.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/