name: safestep
description: "A new Flutter project for personal safety."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.8
  geolocator: ^14.0.2
  flutter_map: ^8.0.0
  latlong2: ^0.9.1
  geocoding: ^3.0.0
  
  # Core Firebase (Unified Generation)
  firebase_core: ^3.10.1
  
  # Auth & Login (Stable & Compatible)
  firebase_auth: ^5.5.0
  google_sign_in: ^7.2.0
  
  # Database & Storage
  cloud_firestore: ^5.6.2
  firebase_storage: ^12.4.2
  
  # Utilities
  url_launcher: ^6.3.1
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/